### ISSUE TITLE
I am an Isaac fan too, but that is cheating.

### ISSUE THREAD

**Issue by olesgedz** [JulienMousset/Doom-Nukem#1]
Subjects states that you need a new engine that allows map have a different levels and heights / skybox etc and not just repeat of  wolf3d with some bonuses. what a shame, but you a getting -42 from me.
![vc](https://user-images.githubusercontent.com/8808075/112805710-a137cd80-907e-11eb-9827-3736bfd5418e.png)

**Comment by JulienMousset** [comment]
Instead of coming at me like that, look at the correction first.
You will see that it states things differently than the subject, otherwise I wouldn't have pass it.
Have a nice day !
